name: Simple Cinema
favicon: null
layout_spectrum: 0.52324
typography_spectrum: 0.4155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ece8dd'
    - '#447886'
    - '#a0b2b2'
    - '#859ea2'
    - '#001a25'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
